# golangci-lint v2 Strict Configuration
# Copy to project root

version: "2"

linters:
  default: all
  disable:
    - depguard          # Dependency guard (project-specific)
    - exhaustruct       # Require all struct fields (too strict)
    - ireturn           # Accept interfaces, return concrete
    - varnamelen        # Variable name length
    - wrapcheck         # Error wrapping (manual)
    - nlreturn          # Newline before return
    - wsl               # Whitespace linter

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  govet:
    enable-all: true
    disable:
      - fieldalignment

  revive:
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: var-naming
      - name: receiver-naming
      - name: unexported-return
      - name: indent-error-flow

  gosec:
    severity: medium
    confidence: medium

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

exclusions:
  warn-unused: true
  presets:
    - comments
    - std-error-handling
    - common-false-positives

  rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - goconst

    - path: \.pb\.go$
      linters:
        - all

output:
  formats:
    - format: colored-line-number
  sort-results: true
